INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Wayne Enterprises');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Stark Industries');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Acme Corporation');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Umbrella Corporation');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Gringotts');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Tyrell Corporation');
INSERT INTO `silicon_bay`.`client` (`clientName`) VALUES ('Wonka Industries');

INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('1', 'BatcaveServer01');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('2', 'los_angeles_001');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('3', 'FairfieldNewJersey');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('4', 'tokyo-1');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('5', 'da_london');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('6', 'LosAngelesSrvr');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('7', 'munich');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('1', 'GothamMain01');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('3', 'TucsonArizona');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('5', 'ccr_london');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('3', 'AlbuquerqueNewMexico');
INSERT INTO `silicon_bay`.`server` (`clientID`, `serverName`) VALUES ('5', 'hgsmd_scotland');

INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('Active Directory');
INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('Domain Controller');
INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('DHCP');
INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('DNS');
INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('File Server');
INSERT INTO `silicon_bay`.`role` (`role`) VALUES ('SQL Server');

INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('1', '1');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('2', '1');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('3', '1');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('4', '1');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('6', '8');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('5', '2');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('1', '3');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('2', '3');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('3', '9');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('4', '11');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('1', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('2', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('3', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('4', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('5', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('6', '4');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('1', '5');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('2', '5');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('3', '10');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('4', '10');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('5', '12');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('6', '12');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('4', '6');
INSERT INTO `silicon_bay`.`serverrole` (`roleID`, `serverID`) VALUES ('6', '7');

INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('1', '/backups/', '/CustomerBackup/5920', '28', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('2', '/bak/', '/CustomerBackup/9503', '14', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('2', '/bak/', '/CustomerBackup/1932', '14', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('3', '/acme/backup', '/CustomerBackup/4920', '56', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('4', '/umbrellacorp/bak/', '/CustomerBackup/4021', '7', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('4', '/umbrellacorp/bak/', '/CustomerBackup/3019', '7', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('4', '/umbrellacorp/bak/', '/CustomerBackup/5419', '7', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('4', '/umbrellacorp/bak/', '/CustomerBackup/4195', '7', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('5', '/gottsbackup/', '/CustomerBackup/9843', '28', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('5', '/gottsbackup/', '/CustomerBackup/6798', '28', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('6', '/dns/backup', '/CustomerBackup/3542', '14', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('6', '/dns/backup', '/CustomerBackup/9098', '14', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('6', '/dns/backup', '/CustomerBackup/1029', '14', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('7', '/mysql/backups', '/CustomerBackup/4756', '56', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('8', '/backups/', '/CustomerBackup/1256', '28', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('8', '/backups/', '/CustomerBackup/3589', '28', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('9', '/acme/backup', '/CustomerBackup/4301', '28', 'onprem');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('10', '/gottsbackup/', '/CustomerBackup/4433', '28', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('10', '/gottsbackup/', '/CustomerBackup/6941', '28', 'cloud');
INSERT INTO `silicon_bay`.`backup` (`serverID`, `backupSource`, `backupDestination`, `frequency`, `notes`) VALUES ('12', '/gottsbackup/', '/CustomerBackup/4311', '28', 'onprem');
